# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stereo-Knowledge Distillation from dpMV to Dual Pixels for Light Field Video Reconstruction
email: raghavmallampalli1234@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Dual pixels contain disparity cues arising from the defocus blur. This disparity information is useful for many vision tasks
ranging from autonomous driving to 3D creative realism. However, directly estimating disparity from dual pixels is less accurate. This
work hypothesizes that distilling high-precision dark stereo knowledge, implicitly or explicitly, to efficient dual-pixel student networks
enables faithful reconstructions. This dark knowledge distillation should also alleviate stereo-synchronization setup and calibration
costs while dramatically increasing parameter and inference time efficiency.
  We collect the first and largest 3-view dual-pixel video
dataset, dpMV, to validate our explicit dark knowledge distillation hypothesis. We show that these methods outperform purely
monocular solutions, especially in challenging foreground-background separation regions using faithful guidance from dual pixels.
Finally, we demonstrate an unconventional use case unlocked by dpMV and implicit dark knowledge distillation from an ensemble of
teachers for Light Field (LF) video reconstruction.
  Our LF video reconstruction method is the fastest and most temporally consistent to
date. It remains competitive in reconstruction fidelity while offering many other essential properties like high parameter efficiency,
implicit disocclusion handling, zero-shot cross-dataset transfer, geometrically consistent inference on higher spatial-angular
resolutions, and adaptive baseline control. All source code will be made available at the anonymous repository https://github.com/ANonyMouxe.
url: "https://raghavmallampalli.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  raghavmallampalli

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
